application: appcontgae
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /maps
  script: main.app
  
- url: /upload
  script: main.app

- url: /.*
  script: helloworld.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: latest

builtins:
- remote_api: on
